### ISSUE TITLE
Map does not work. 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Zemma-Hammerman-Site#11]
In all projects Google man is not working. 
this is the error that is showing in console.
![image](https://cloud.githubusercontent.com/assets/26923359/26400273/e3850c06-4088-11e7-84f8-de70520f12b8.png)

**Comment by MeanEYE** [comment]
Should be fixed. Wait at least 15min after this message to try.

**Comment by talovdat** [comment]
Still not working.
