### ISSUE TITLE
Add link in bottom menu

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Zemma-Hammerman-Site#18]
Add link in the bottom menu. 
Link title: קשרי משקיעים
Link it self: ir.zhg.co.il

Place it in the next location: 
![image](https://user-images.githubusercontent.com/26923359/29872466-6d62f3aa-8d98-11e7-80ea-9e164558f50a.png)

**Comment by MeanEYE** [comment]
Open in new tab?

**Comment by talovdat** [comment]
No, same tab.

**Comment by VladimirWebDev** [comment]
@talovdat   ir.zhg.co.il is url for link..?

**Comment by talovdat** [comment]
Yes.

**Comment by MeanEYE** [comment]
We didn't make that one Tal

**Comment by MeanEYE** [comment]
@VladimirWebDev what's the confusion with this one?

**Comment by VladimirWebDev** [comment]
Just checking if url is correct because on that url (ir.zhg.co.il) is WordPress example site..

**Comment by MeanEYE** [comment]
Okay, so to explain... link should be added in this repository. URL provided is the `href` part of the link. So link should go to `ir.zhg.co.il` not be added on it.
