### ISSUE TITLE
Site looks bad on Chrome browser(Desktop)

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Zemma-Hammerman-Site#19]
Site looks bad Only on Chrome browser. 
![image](https://user-images.githubusercontent.com/26923359/30054317-5f8697d2-9234-11e7-95c4-a87be5d6f751.png)

**Comment by MeanEYE** [comment]
@VladimirWebDev, @eyalway2cu and @hanan-avzuk I need confirmation on this one.

**Comment by talovdat** [comment]
Checked on Eyal pc and two more laptops and it looks fine.
No issue here, my fault.

**Comment by talovdat** [comment]
Should I close the issue?
