### ISSUE TITLE
CRM (bmby) not receiving leads from site

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Zemma-Hammerman-Site#23]
Client claims that Bmby is not receiving any leads from the site.

Closed issue number 12 dealt with API and missing information.
Please take a personal look at that issue, might be the same one.

Issue subject:
Missing information to be sent through API. #12

**Comment by MeanEYE** [comment]
What is is exactly that they want done? Since we keep coming back to this.

**Comment by talovdat** [comment]
Client addressed me with this issue, claiming that their CRM is not
receiving leads from http://zhg.co.il/
And she has to update every lead manually.

**Comment by MeanEYE** [comment]
I got that from the first comment, but originally the deal was send leads with some projects but not all of them. What is not clear here is which projects are not receiving leads?

**Comment by talovdat** [comment]
According to client, this issue apply to all projects.
