### ISSUE TITLE
Remove red and change text at the homepage link

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Zemma-Hammerman-Site#26]
Remove red and change the text of the home page link. 
Now saying - "Home page" 
Should say - "Home" 

Hebrew:
עמוד הבית should change to בית

![image](https://user-images.githubusercontent.com/26923359/31584628-d6a586ca-b1ba-11e7-8722-c8fc2b9f2806.png)

**Comment by MeanEYE** [comment]
Only CSS should be changed. We need to change it from red text color to `text-decoration: underline`.
