### ISSUE TITLE
GTM code implanting 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Zemma-Hammerman-Site#27]
We need to implant GTM code on the site.

**Comment by talovdat** [comment]
Code is attached to an email sent to developers address. 
Email subject: GTM code for Zemmah Hamerman site

**Comment by talovdat** [comment]
Somehow, a part of the code is showing on the site:

![image](https://user-images.githubusercontent.com/26923359/40971700-2292c764-68c7-11e8-9b30-333826d6fbb4.png)

**Comment by MeanEYE** [comment]
There's no somehow. @VladimirWebDev just copy pasted without looking.

**Comment by VladimirWebDev** [comment]
I haven't look inside that file. Just included it on required pages. Someone added note that it should be on all pages. Will fix.. I apologize for not looking..
