### ISSUE TITLE
Mobile menu is broken.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Zemma-Hammerman-Site#9]
![image](https://cloud.githubusercontent.com/assets/1911594/25618525/8da43d0e-2f47-11e7-928e-1c42961b742c.png)

As seen on screen shot mobile menu is broken.

**Comment by iliyaM** [comment]
On what Page?

בתאריך 2 במאי 2017 15:57,‏ "Mladen Mijatov" <notifications@github.com> כתב:
